name: ECS Deploy

on:
  workflow_call:
    inputs:
      branch-name:
        required: true
        type: string
      repository-name:
        required: true
        type: string
      brand-name:
        required: true
        type: string
      build-envs:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      NPM_TOKEN:
        required: false
      NPM_REGISTRY:
        required: false
        
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variables dynamically
        run: |
          BRANCH_NAME="${{ inputs.branch-name }}"
          REPOSITORY_NAME="${{ inputs.repository-name }}"
          BRAND_NAME="${{ inputs.brand-name }}"
          case "$BRANCH_NAME" in
            "dev")
              ENV="dev"
              CLUSTER_SUFFIX="dev"
              DOMAIN_SUFFIX="dev"
              ;;
            "staging")
              PUBLIC_KEY=${{ secrets.SCROLL_STAGING_PUBLIC_KEY }}
              PRIVATE_KEY=${{ secrets.SCROLL_STAGING_PRIVATE_KEY }}
              ENV="staging"
              CLUSTER_SUFFIX="staging"
              DOMAIN_SUFFIX="staging"
              TCENTER_PAY="https://payments.staging.tcenter.cloud"
              TCENTER_SSO="https://sso.staging.tcenter.cloud"
              PRIVATE_KEY="3cca83ec-737f-426c-a99b-2675551c9a98"
              PUBLIC_KEY="67fd6192-f277-4a82-b626-3706212ae8eb"
              APP_PRIVATE="30b8e3d7-a571-4550-b91f-06ce8a6bbb0b"
              APP_PUBLIC="c9c5a0d7-8ea1-40b9-a3ab-5da9bd23c9f1"
              ;;
            "main")
              PUBLIC_KEY=${{ secrets.SCROLL_PROD_PUBLIC_KEY }}
              PRIVATE_KEY=${{ secrets.SCROLL_PROD_PRIVATE_KEY }}
              ENV="prod"
              DOMAIN_SUFFIX="app"
              CLUSTER_SUFFIX="prod"
              TCENTER_PAY="https://payments.tcenter.cloud"
              TCENTER_SSO="https://sso.tcenter.cloud"
              PRIVATE_KEY="661cd8a7-aa43-4887-b840-9a039bf5dd5a"
              PUBLIC_KEY="c5774b8b-6c03-40ff-a1e8-c477d7010ade"
              APP_PRIVATE="ab0348be-f179-4e48-83f8-a4b6e45e03ac"
              APP_PUBLIC="b3ab0d04-bc8d-4644-a651-5449dc3dac1e"
              ;;
            *)
              echo "Unknown branch name: $BRANCH_NAME"
              exit 1
              ;;
          esac
          CLUSTER_NAME="scr-${CLUSTER_SUFFIX}-cluster"
          SERVICE_NAME="scr-${CLUSTER_SUFFIX}-${REPOSITORY_NAME}"

          echo "ENV=$ENV" >> $GITHUB_ENV
          echo "CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          echo "DOMAIN_SUFFIX=$DOMAIN_SUFFIX" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        
        run: |
        
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${SERVICE_NAME}:latest \
            --build-arg REACT_APP_CUSTOMER_MANAGEMENT_API_PROXY_URL="https://api.${DOMAIN_SUFFIX}.scroll.codes/customersManage" \
            --build-arg REACT_APP_BRANCHES_VEHICLES_API_PROXY_URL="https://api.${DOMAIN_SUFFIX}.scroll.codes/vehiclesApi" \
            --build-arg REACT_APP_VEHICLES_SOCKET_PROXY="https://ws.${DOMAIN_SUFFIX}.scroll.codes:8006" \
            --build-arg REACT_APP_AUTHORIZATION_API_PROXY_URL="${TCENTER_SSO}" \
            --build-arg REACT_APP_PAYMENTS_API_PROXY_URL="${TCENTER_PAY}" \
            --build-arg REACT_APP_BACKOFFICE_PRIVATE_KEY="${PRIVATE_KEY}" \
            --build-arg REACT_APP_BACKOFFICE_PUBLIC_KEY="${PUBLIC_KEY}" \
            --build-arg REACT_SCROLL_APP_PRIVATE="${APP_PRIVATE}" \
            --build-arg REACT_SCROLL_APP_PUBLIC="${APP_PUBLIC}" \
            --build-arg REACT_APP_VEHICLES_RENTALS_API_PROXY_URL="https://api.${DOMAIN_SUFFIX}.scroll.codes/rentalsApi" .
            
          docker push ${{ steps.login-ecr.outputs.registry }}/${SERVICE_NAME}:latest


      - name: Force new deployment in ECS
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
